### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by michalczaplinski** [electron-userland/devtron#111]
Can it be considered deprecated?
Do we have better alternatives?

**Comment by doortts** [comment]
I think this project is dead or as same as dead.

**Comment by pd4d10** [comment]
We use it in [our project](https://github.com/bytedance/debugtron). I'd like to help if there is no active maintainer.

**Comment by doortts** [comment]
@pd4d10 How about forking? If you can, I'd like to support you.

**Comment by pd4d10** [comment]
@doortts I've noticed that this lib is used by [17k repos](https://github.com/electron-userland/devtron/network/dependents?package_id=UGFja2FnZS0xNjQwOTcyOA%3D%3D). Probably it is better to continue maintaining this project (If possible)? So these users could get updates without tweaking their projects' dependencies.

**Comment by pd4d10** [comment]
Hi, @doortts , repo here: https://github.com/pd4d10/devtron

Since there are significant changes in the tech stack (TypeScript + React + Webpack), I choose to create a new repo instead of a fork.

**Comment by doortts** [comment]
@pd4d10 Awesome!! 👍

**Comment by erickzhao** [comment]
See #200
