### ISSUE TITLE
require('devtron').install()

### ISSUE THREAD

**Issue by ar414-com** [electron-userland/devtron#167]
Node.js 12.13.0
Chromium 80.0.3987.86
Electron 8.0.0
````
[13228:0213/235937.927:ERROR:CONSOLE(7)] "Uncaught TypeError: Cannot read property 'panels' of undefined", source: chrome-extension://devtron/static/devtron.html (7) 
````

**Comment by ar414-com** [comment]
main.js
```JavaScript
const {app,BrowserWindow} = require('electron');

app.allowRendererProcessReuse = false;

app.on('ready',() => {
    require('devtron').install()
    //主窗口
    let mainWindow = new BrowserWindow({
        width:1200,
        height:800,
        webPreferences: {
            //可以使用nodejs
            nodeIntegration: true
        }
    })

    mainWindow.loadFile('index.html')
    //开发者工具
    mainWindow.webContents.openDevTools()
    //子窗口
    // let secondWindow = new BrowserWindow({
    //     width:800,
    //     height:600,
    //     parent:mainWindow,
    //     webPreferences:{
    //         nodeIntegration: true
    //     }
    // });
    // secondWindow.loadURL("https://www.acfun.cn/");
});
```

**Comment by LDubya** [comment]
Also getting this

Node v 12.10.0
also on 8.12.0

Electron 8

`"Uncaught TypeError: Cannot read property 'panels' of undefined", source: chrome-extension://devtron/static/devtron.html (7)`

**Comment by mengdebiao** [comment]
请问这个问题最后你是如何解决的？

**Comment by mengdebiao** [comment]
> main.js
> 
> ```js
> const {app,BrowserWindow} = require('electron');
> 
> app.allowRendererProcessReuse = false;
> 
> app.on('ready',() => {
>     require('devtron').install()
>     //主窗口
>     let mainWindow = new BrowserWindow({
>         width:1200,
>         height:800,
>         webPreferences: {
>             //可以使用nodejs
>             nodeIntegration: true
>         }
>     })
> 
>     mainWindow.loadFile('index.html')
>     //开发者工具
>     mainWindow.webContents.openDevTools()
>     //子窗口
>     // let secondWindow = new BrowserWindow({
>     //     width:800,
>     //     height:600,
>     //     parent:mainWindow,
>     //     webPreferences:{
>     //         nodeIntegration: true
>     //     }
>     // });
>     // secondWindow.loadURL("https://www.acfun.cn/");
> });
> ```

我也是这么写的，但是 devtron 还是没出来，请问您是怎么解决的呢？

**Comment by cSarcasme** [comment]
Hi,
anyone find the solution to his error ?

have a nice day

**Comment by Chad97** [comment]
Installing Devtron ` /xxx/node_modules/_devtron@1.4.0@devtron`

this await ⬆️

**Comment by Chad97** [comment]
Is anyone maintaining?
Is this warehouse deprecated?

**Comment by nickylogan** [comment]
I followed the logged errors and changed some fields in the `manifest.json` file and seems to work for me:

```json
{
  "name": "devtron",
  "version": "1.0",
  "manifest_version": 2,
  "devtools_page": "static/devtron.html",
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["out/browser-globals.js"]
    }
  ],
  "content_security_policy": "script-src 'self' 'sha256-oUhBdPf7Ru2sGu4k6v1SmxAkpoPTuzvsLrUqElYwDRE='"
}
```

Use [patch-package](https://www.npmjs.com/package/patch-package) to create the patch.

Hope it helps 🙌

**Comment by scottpageindysoft** [comment]
@nickylogan I came here to solve the same issue as everyone else, and I'm leaving happy thanks to you for pointing out patch-package.  Not for the fix to this issue, but I wasn't aware of it before, and it's a life saver for my projects.

Thanks! 👍

**Comment by scottpage** [comment]
Despite my disdain for the recent disgusting behaviour of the the core Electron team, thinking that every developer is also a BLM supporter, I'll pick this lump of shit up and attempt to get it working again.  I see a lot of need for it amongst others, I need a tool like this, and I'm also not an asshole.  Unlike the Electron team, that seems to push people away and get in to politics.

Electron team, you do you, I'll finish.

**Comment by ar414-com** [comment]
What I have learned at the moment is the version update of the conversion electron. The electron-userland/devtron is not updated with the electron update (the last submission was 3 years ago). This is the description of electron in 2020 about loading extensions.
https://github.com/electron/electron/blob/master/docs/api/extensions.md

**Comment by nonchip** [comment]
> @scottpage: Unlike the Electron team, that seems to push people away and get in to politics.

says the asshole who commented just to push this into his white supremacy politics.

---

Back to topic:

> ￼ @ar414-com  closed this on Aug 3

dare to say why? the issue still persists.

**Comment by cnscorpions** [comment]
Hello all you guys, 

I found a workaroud,

1. follow @nickylogan all steps
2. go your local node modules devtron, copy absolute path
3. import this extension into your electron app as follows:
```
const launchDevtron = window => {
  try {
    window.addDevToolsExtension(
      "F:\\**************\\node_modules\\devtron"
    );
  } catch (error) {
    console.log(error);
  }
};

// import before ready lifecycle
app.whenReady().then(() => {
  if (isDev) {
    const { launchDevtron } = require("./devtool");
    launchReduxDevTool(BrowserWindow);
    launchDevtron(BrowserWindow);
  }
});

```

Then tada, hope it works 😉
